# Generated by Django 6.0.5 on 2026-05-18 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_harga', models.IntegerField()),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu Pembayaran'), ('PROSES', 'Sedang Diproses'), ('KIRIM', 'Sedang Dikirim'), ('SELESAI', 'Selesai'), ('BATAL', 'Dibatalkan')], default='MENUNGGU', max_length=20)),
                ('catatan', models.TextField(blank=True, help_text='Catatan tambahan dari pembeli', null=True)),
                ('nama_penerima', models.CharField(max_length=100)),
                ('telepon', models.CharField(max_length=20)),
                ('alamat_lengkap', models.TextField()),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diperbarui', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesanan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daftar Pesanan',
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='produk/thumbnails/')),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('harga', models.IntegerField()),
                ('stok', models.IntegerField(default=0)),
                ('is_flash_sale', models.BooleanField(default=False)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produk', to='toko.kategori')),
            ],
            options={
                'verbose_name_plural': 'Produk',
            },
        ),
        migrations.CreateModel(
            name='DetailPesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('harga_saat_beli', models.IntegerField()),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='toko.pesanan')),
                ('produk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toko.produk')),
            ],
            options={
                'verbose_name_plural': 'Detail Item Pesanan',
            },
        ),
        migrations.CreateModel(
            name='ProdukGambar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='produk/galeri/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeri', to='toko.produk')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('komentar', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='toko.produk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produk_disukai', to=settings.AUTH_USER_MODEL)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='toko.produk')),
            ],
            options={
                'unique_together': {('user', 'produk')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='toko.produk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produk_wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'produk')},
            },
        ),
    ]
