# Generated by Django 6.0.5 on 2026-05-15 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='produk/')),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('harga', models.IntegerField()),
                ('stok', models.IntegerField(default=0)),
                ('is_flash_sale', models.BooleanField(default=False)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produk', to='toko.kategori')),
            ],
            options={
                'verbose_name_plural': 'Produk',
            },
        ),
    ]
