# Generated by Django 6.0.5 on 2026-05-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='video_produk',
            field=models.FileField(blank=True, null=True, upload_to='produk/videos/'),
        ),
    ]
