# Generated by Django 6.0.5 on 2026-05-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='flash_sale_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
