# Generated by Django 6.0.5 on 2026-05-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0002_produk_flash_sale_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='kurir',
            field=models.CharField(blank=True, choices=[('jne', 'JNE Express'), ('jnt', 'J&T Express'), ('sicepat', 'SiCepat'), ('pos', 'POS Indonesia'), ('anteraja', 'AnterAja'), ('tiki', 'TIKI')], help_text='Pilih ekspedisi pengiriman', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='no_resi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomor Resi'),
        ),
    ]
