# Generated by Django 6.0.5 on 2026-05-15 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0002_like_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='produk/thumbnails/'),
        ),
        migrations.CreateModel(
            name='ProdukGambar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='produk/galeri/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeri', to='toko.produk')),
            ],
        ),
    ]
