# Generated by Django 6.0.5 on 2026-05-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0003_pesanan_kurir_pesanan_no_resi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='kurir_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='kurir_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='status_kurir',
            field=models.CharField(default='gudang', max_length=20),
        ),
    ]
