# Generated by Django 6.0.5 on 2026-06-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0004_pesanan_kurir_lat_pesanan_kurir_lon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(help_text='Nama promo (contoh: Concert Season Deal)', max_length=150)),
                ('gambar', models.ImageField(help_text='Rekomendasi ukuran banner e-commerce: 1200x450 piksel', upload_to='banners/')),
                ('url_tujuan', models.CharField(blank=True, help_text='Link tujuan saat diklik (contoh: /kategori/serum/ atau link eksternal)', max_length=255, null=True)),
                ('is_aktif', models.BooleanField(default=True, help_text='Centang untuk menampilkan di halaman utama')),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Banner Promo Beranda',
            },
        ),
    ]
