# Generated by Django 6.0.5 on 2026-05-18 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0004_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_harga', models.IntegerField()),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu Pembayaran'), ('PROSES', 'Sedang Diproses'), ('KIRIM', 'Sedang Dikirim'), ('SELESAI', 'Selesai'), ('BATAL', 'Dibatalkan')], default='MENUNGGU', max_length=20)),
                ('catatan', models.TextField(blank=True, help_text='Catatan tambahan dari pembeli', null=True)),
                ('nama_penerima', models.CharField(max_length=100)),
                ('telepon', models.CharField(max_length=20)),
                ('alamat_lengkap', models.TextField()),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diperbarui', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesanan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daftar Pesanan',
            },
        ),
        migrations.CreateModel(
            name='DetailPesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('harga_saat_beli', models.IntegerField()),
                ('produk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toko.produk')),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='toko.pesanan')),
            ],
            options={
                'verbose_name_plural': 'Detail Item Pesanan',
            },
        ),
    ]
