# Generated by Django 6.0.6 on 2026-06-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0005_bannerpromo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='kode_pos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
