# Generated by Django 6.0.6 on 2026-06-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0006_pesanan_kode_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='lokasi_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='lokasi_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
