# Generated by Django 6.0.6 on 2026-08-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0007_pesanan_lokasi_lat_pesanan_lokasi_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='doku_invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='doku_payment_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
